### ISSUE TITLE
Gold furnace server crash

### ISSUE THREAD

**Issue by 3dguru** [Qelifern/IronFurnaces#10]
Making gold furnace adding coal block and cooking or smelting causes server to crash. 

Mod version ironfurnaces-1.15.2-2.0.3
Forge 31.2.30

https://pastebin.com/0VxZH5X4

**Comment by XenoMustache** [comment]
Log please?

**Comment by XenoMustache** [comment]
```
[09Jul2020 19:15:18.690] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:853) ~[?:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) ~[?:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
    at net.minecraft.inventory.IRecipeHolder.func_201561_a(SourceFile:27) ~[?:?]
    at ironfurnaces.tileentity.BlockIronFurnaceTileBase.smeltItem(BlockIronFurnaceTileBase.java:284) ~[?:2.0.3]
    at ironfurnaces.tileentity.BlockIronFurnaceTileBase.func_73660_a(BlockIronFurnaceTileBase.java:223) ~[?:2.0.3]
    at net.minecraft.world.World.func_217391_K(World.java:473) ~[?:?]
    at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368) ~[?:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?]
    ... 4 more
```
this is the relevant information, we'll look into it.

**Comment by Qelifern** [comment]
Unable to recreate issue
