### ISSUE TITLE
Furnace disappears when broke

### ISSUE THREAD

**Issue by Jorc0** [Qelifern/IronFurnaces#114]
### Forge Version

40.1.60

### Iron Furnaces Version

3.3.1

### Describe your issue

All furnaces disappear when i break them, error appears on console, link given

### Crash Report

https://gist.github.com/Jorc0/8f7ea6d2c49ff22f62a1cbd390b21b62

**Comment by Qelifern** [comment]
Unable to reproduce

**Comment by derrickmehaffy** [comment]
I can reproduce this on the ATM7 pack: 

```
[30Aug2022 00:39:34.624] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@8157c3, suppressing error
java.lang.ClassCastException: class net.geforcemods.securitycraft.blockentities.DisguisableBlockEntity cannot be cast to class ironfurnaces.tileentity.furnaces.BlockMillionFurnaceTile (net.geforcemods.securitycraft.blockentities.DisguisableBlockEntity is in module securitycraft@1.9.3.1 of loader 'TRANSFORMER' @278fe428; ironfurnaces.tileentity.furnaces.BlockMillionFurnaceTile is in module ironfurnaces@3.3.1 of loader 'TRANSFORMER' @278fe428)
	at ironfurnaces.blocks.furnaces.BlockIronFurnaceBase.m_6810_(BlockIronFurnaceBase.java:262) ~[ironfurnaces-1.18.2-3.3.1.jar%23189!/:3.3.1]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60753_(BlockBehaviour.java:673) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:236) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.world.level.Level.m_6933_(Level.java:201) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.world.level.Level.m_7731_(Level.java:178) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraftforge.common.extensions.IForgeBlock.onDestroyedByPlayer(IForgeBlock.java:168) ~[forge-1.18.2-40.1.68-universal.jar%23355!/:?]
	at net.minecraftforge.common.extensions.IForgeBlockState.onDestroyedByPlayer(IForgeBlockState.java:124) ~[forge-1.18.2-40.1.68-universal.jar%23355!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.removeBlock(ServerPlayerGameMode.java:275) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:258) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:224) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:194) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:952) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23350!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[30Aug2022 00:39:34.640] [Server thread/WARN] [net.minecraft.world.level.chunk.LevelChunk/]: Block entity ironfurnaces:netherite_furnace @ BlockPos{x=46036, y=42, z=8944} state Block{minecraft:air} invalid for ticking:
```

appears to be an issue with securitycraft and iron furnaces

**Comment by derrickmehaffy** [comment]
related issue from securityCraft: https://github.com/Geforce132/SecurityCraft/issues/336
