### ISSUE TITLE
Trying to smelt anything causes server crash (1.16.1)

### ISSUE THREAD

**Issue by tyrus7141** [Qelifern/IronFurnaces#13]
Crash occurs when smelting would normally complete. I can put fuel and an item to be smelted into furnace, but when the item completes the server crashes.
Using newest version of forge and JRE.

[22:15:52] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:81) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5568/289049029.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.inventory.IRecipeHolder.func_201561_a(SourceFile:27) ~[?:?]
	at ironfurnaces.tileentity.BlockIronFurnaceTileBase.smeltItem(BlockIronFurnaceTileBase.java:284) ~[?:2.1.1]
	at ironfurnaces.tileentity.BlockIronFurnaceTileBase.func_73660_a(BlockIronFurnaceTileBase.java:223) ~[?:2.1.1]
	at net.minecraft.world.World.func_217391_K(World.java:533) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:364) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?]
	... 6 more

**Comment by tyrus7141** [comment]
Similar to issue #10, but in 1.16

**Comment by Qelifern** [comment]
Unable to recreate issue
