### ISSUE TITLE
Server Crash after upgrade from 2.5.6 to 2.5.7

### ISSUE THREAD

**Issue by PongoSapiens** [Qelifern/IronFurnaces#28]
**Describe the bug**
Crashes my server after upgrade to latest version

**To Reproduce**
1. Upgrade iron furnaces from 2.5.6 to 2.5.7
2. Start server
3.

**Expected behavior**
The server not to crash.

**Versions**
- **Iron Furnaces**: 2.5.7
- **Forge**: 35.1.29

<details>
  <summary>Crashlog</summary>
  [19:44:44] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: 0
        Index: 8
        Listeners:
                0: NORMAL
                1: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@45379c0f worldTickEvent(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                2: ASM: class com.supermartijn642.chunkloaders.ChunkLoaderUtil onTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                3: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                4: net.minecraftforge.eventbus.EventBus$$Lambda$2691/1266065652@64424463
                5: ASM: class sonar.fluxnetworks.register.CommonEventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                6: ASM: class com.github.alexthe666.rats.server.events.CommonEvents onServerTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                7: ASM: class com.simibubi.create.events.CommonEvents onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                8: ASM: com.refinedmods.refinedstorage.apiimpl.network.NetworkListener@2e51fc7b onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                9: ASM: mcjty.xnet.setup.ForgeEventHandlers@6eb19003 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                10: net.minecraftforge.eventbus.EventBus$$Lambda$2691/1266065652@5f57bc33
                11: ASM: svenhjol.charm.module.SleepImprovements@6ac28d1f onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
java.lang.ArrayIndexOutOfBoundsException: 0
        at ironfurnaces.tileentity.FurnaceSettings.get(FurnaceSettings.java:39)
        at ironfurnaces.blocks.BlockIronFurnaceBase.func_180656_a(BlockIronFurnaceBase.java:271)
        at net.minecraft.block.AbstractBlock$AbstractBlockState.func_185911_a(AbstractBlock.java:485)
        at net.minecraft.world.World.func_175651_c(World.java:849)
        at net.minecraft.world.World.func_175640_z(World.java:856)
        at com.refinedmods.refinedstorage.apiimpl.network.node.NetworkNode.update(NetworkNode.java:142)
        at com.refinedmods.refinedstorage.apiimpl.network.node.ImporterNetworkNode.update(ImporterNetworkNode.java:61)
        at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:25)
        at net.minecraftforge.eventbus.ASMEventHandler_487_NetworkListener_onWorldTick_WorldTickEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
        at java.lang.Thread.run(Thread.java:748)

<details>

**Comment by Qelifern** [comment]
https://github.com/Qelifern/IronFurnaces/issues/30
