### ISSUE TITLE
Ticking Entity Error

### ISSUE THREAD

**Issue by MrTailson** [Qelifern/IronFurnaces#39]
**Describe the bug**
The game crashes for other players when they join my world while any form of an Iron Furnace is placed down in the world.

**To Reproduce**
1. Place down an Iron (Or any of the upgrades) Furnace
2. Have another player (who also has the same mods and versions as necessary to join) join in the world.
3. They should crash and be given a Ticking Entity error

**Expected behavior**

**Versions**
- **Iron Furnaces**: 1.16.5-2.6.3
- **Forge**: 1.16.5 - 36.0.22
- **Fabric**: x.x.x

<details>
  <summary>Crashlog</summary>
  Log goes here
---- Minecraft Crash Report ----
// You're mean.

Time: 2/11/21 5:35 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at harmonised.pmmo.util.XP.checkBiomeLevelReq(XP.java:1581) ~[?:1.16.4-3.44.2] {re:classloading}
	at harmonised.pmmo.events.PlayerTickHandler.handlePlayerTick(PlayerTickHandler.java:79) ~[?:1.16.4-3.44.2] {re:classloading}
	at harmonised.pmmo.events.EventHandler.playerTick(EventHandler.java:55) ~[?:1.16.4-3.44.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_149_EventHandler_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2604/1173227977.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.entity.player.RemoteClientPlayerEntity.func_70071_h_(RemoteClientPlayerEntity.java:37) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld$$Lambda$7767/1745985832.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.22.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/1370169059.call(Unknown Source) [forge-1.16.5-36.0.22.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at harmonised.pmmo.util.XP.checkBiomeLevelReq(XP.java:1581) ~[?:1.16.4-3.44.2] {re:classloading}
	at harmonised.pmmo.events.PlayerTickHandler.handlePlayerTick(PlayerTickHandler.java:79) ~[?:1.16.4-3.44.2] {re:classloading}
	at harmonised.pmmo.events.EventHandler.playerTick(EventHandler.java:55) ~[?:1.16.4-3.44.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_149_EventHandler_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2604/1173227977.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.entity.player.RemoteClientPlayerEntity.func_70071_h_(RemoteClientPlayerEntity.java:37) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld$$Lambda$7767/1745985832.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.RemoteClientPlayerEntity)
	Entity ID: 229
	Entity Name: Mr_Tailson
	Entity's Exact location: 527.30, 36.00, 84.95
	Entity's Block location: World: (527,36,84), Chunk: (at 15,2,4 in 32,5; contains blocks 512,0,80 to 527,255,95), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:classloading,xf:OptiFine:default}

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['blademiss'/63268, l='ClientLevel', x=463.36, y=63.00, z=146.53], RemoteClientPlayerEntity['Mr_Tailson'/229, l='ClientLevel', x=527.30, y=36.00, z=84.95]]
	Chunk stats: Client Chunk Cache: 3969, 2916
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11 game time, 11 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.22.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/1370169059.call(Unknown Source) [forge-1.16.5-36.0.22.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 959618272 bytes (915 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.22.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.22.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.22.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.22.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.22
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.22-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		DungeonsMod-1.16.3-1.1.18.jar                     |Dungeons Mod                  |dungeonsmod                   |1.16.3-1.1.18       |DONE      |NOSIGNATURE
		Ping-1.16.4-1.6.9.jar                             |Ping                          |ping                          |1.16.4-1.6.9        |DONE      |NOSIGNATURE
		SilentLib-1.16.3-4.9.1+64.jar                     |Silent Lib                    |silentlib                     |4.9.1+64            |DONE      |NOSIGNATURE
		surrounding-indicators-1.16.4-1.1.2.jar           |Surrounding Indicators        |surrounding_indicators        |1.1.2               |DONE      |NOSIGNATURE
		ironfurnaces-1.16.5-2.6.3.jar                     |Iron Furnaces                 |ironfurnaces                  |2.6.3               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
		simplefarming-1.16.4-1.3.5.jar                    |Simple Farming                |simplefarming                 |1.16.4-1.3.5        |DONE      |NOSIGNATURE
		giacomos_bookshelf1.3_1.16.3.jar                  |Giacomo's bookshelves Mod     |giacomos_bookshelf            |1.3                 |DONE      |NOSIGNATURE
		AttributeFix-1.16.5-10.0.1.jar                    |AttributeFix                  |attributefix                  |10.0.1              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		storage_overhaul-1.16.5-1.0.0.jar                 |Storage Overhaul              |storage_overhaul              |1.16.5-1.0.0        |DONE      |NOSIGNATURE
		jeiintegration_1.16.5-7.0.0.12.jar                |JEI Integration               |jeiintegration                |7.0.0.12            |DONE      |NOSIGNATURE
		NorthernCompass-Forge-1.16.5-1.0.4.jar            |NorthernCompass               |northerncompass               |1.16.5-1.0.4        |DONE      |65:9c:b2:1c:ac:92:df:f0:35:07:78:51:9b:65:49:87:69:0b:76:7f:23:9a:ab:1f:fa:fc:b0:f3:fc:02:6a:1b
		curios-forge-1.16.5-4.0.4.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.4.0      |DONE      |NOSIGNATURE
		randomite-1.16.4-1.0.1.jar                        |Randomite Classic             |randomite                     |1.0.1               |DONE      |NOSIGNATURE
		gravestone-1.16.5-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.1        |DONE      |NOSIGNATURE
		collective-1.16.5-1.59.jar                        |Collective                    |collective                    |1.59                |DONE      |NOSIGNATURE
		CookingForBlockheads_1.16.3-9.2.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.2.2               |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |DONE      |NOSIGNATURE
		TravelersBackpack-1.16.4-5.3.8.jar                |Traveler's Backpack           |travelersbackpack             |5.3.8               |DONE      |NOSIGNATURE
		sit-1.16.2-v1.3.jar                               |Sit                           |sit                           |v1.3                |DONE      |NOSIGNATURE
		simplytea-1.16.5-2.3.4.jar                        |Simply Tea                    |simplytea                     |2.3.4               |DONE      |NOSIGNATURE
		gemsnjewels-1.16.4-0.21.0.jar                     |Gems & Jewels                 |gemsnjewels                   |0.21.0              |DONE      |NOSIGNATURE
		curioofundying-forge-1.16.4-5.1.0.0.jar           |Curio of Undying              |curioofundying                |1.16.4-5.1.0.0      |DONE      |NOSIGNATURE
		culinaryconstruct-forge-1.16.5-4.0.0.4.jar        |Culinary Construct            |culinaryconstruct             |1.16.5-4.0.0.4      |DONE      |NOSIGNATURE
		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		EnchantmentDescriptions-1.16.5-7.0.3.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.3               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BetterHurtTimer-1.16.3-4.4.0.2.jar                |Better Hurt Timer             |betterhurttimer               |1.16.3-4.4.0.2      |DONE      |c9:84:cd:eb:27:ac:0d:ad:8c:55:6f:d6:5f:19:f2:c8:63:2a:b0:bd:3b:d0:b6:df:fd:9f:de:9f:9d:e8:7c:68
		Actually.Useful.Smithing.Table-1.0.2.mc.1.16.3.jar|Actually Useful Smithing Table|actuallyusefulsmithingtable   |1.0.2 mc 1.16.3     |DONE      |NOSIGNATURE
		Apotheosis-1.16.3-4.4.1.jar                       |Apotheosis                    |apotheosis                    |4.4.1               |DONE      |NOSIGNATURE
		Project_MMO-1.16.4-3.44.2.jar                     |Project MMO                   |pmmo                          |1.16.4-3.44.2       |DONE      |NOSIGNATURE
		globalxp-1.16.5-v1.5.jar                          |Global XP                     |globalxp                      |v1.5                |DONE      |NOSIGNATURE
		mvw-1.6.1.jar                                     |MoreVanillaWeapons            |mvw                           |1.16.X-1.6.1        |DONE      |NOSIGNATURE
		carryon-1.16.3-1.15.1.7.jar                       |Carry On                      |carryon                       |1.15.1.7            |DONE      |8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		BetterShieldsMC1.16.3-1.1.4.jar                   |Better Shields                |bettershields                 |1.1.4               |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.22-universal.jar                |Forge                         |forge                         |36.0.22             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		Aquaculture-1.16.5-2.1.13.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.13       |DONE      |NOSIGNATURE
		mineralchance_1.16.5-1.1.jar                      |Mineral Chance                |mineralchance                 |1.1                 |DONE      |NOSIGNATURE
		infinitetrading_1.16.5-1.3.jar                    |Infinite Trading              |infinitetrading               |1.3                 |DONE      |NOSIGNATURE
		ScalingHealth-1.16.4-4.0.3+3.jar                  |Scaling Health                |scalinghealth                 |4.0.3+3             |DONE      |NOSIGNATURE
		supplementaries-1.16.5-0.9.24b.jar                |Supplementaries               |supplementaries               |1.16.5-0.9.24b      |DONE      |NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |DONE      |NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0.jar                   |GeckoLib                      |geckolib3                     |3.0.0               |DONE      |NOSIGNATURE
		BetterAdvancements-1.16.4-0.1.0.104.jar           |Better Advancements           |betteradvancements            |0.1.0.104           |DONE      |NOSIGNATURE
	Crash Report UUID: c051646b-e02e-46b7-a382-90afe25a5924
	Launched Version: 1.16.5-forge-36.0.22
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.40, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.01pre2.zip
	OpenGlVersion: 4.6.0 NVIDIA 461.40
	OpenGlRenderer: GeForce RTX 2060 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

<details>

**Comment by XenoMustache** [comment]
Closed because according to the crashlog this has nothing to do with Iron Furnaces.
